### ISSUE TITLE
⚠️ CONTACT REQUEST!! ⚠️

### ISSUE THREAD

**Issue by toxic-devil** [ariffb25/ily#1]
Hey @ariffb25!! 👋

**Can We Contact Each Other** @ariffb25 
Please Give me a Way To Contact You @ariffb25 

*Its Urgent* @ariffb25 

  - Its Me TOXIC-DEVIL 🤫

**Comment by ariffb25** [comment]
wa.me/6283128734012 here's my whatsapp

**Comment by TOXIC-DEVIL** [comment]
> wa.me/6283128734012 here's my whatsapp

Hey!! I am not comfortable with whatsapp 😔 Let me get your ig id? 😁

**Comment by TOXIC-DEVIL** [comment]
Contacted 😂
